[console]
"start_with_header" = true
"clear_on_start" = true
"prompt_prefix" = "DEFAULT"
"default_color" = "0a"
"add_spacing_on_prompt" = true

"gpkg_files_needed" = true

"path_plugin" = "DEFAULT"

[font]
"change_font" = false
"font_name" = "Courier New"